Keyboard state
Alexays/Waybar pull request #1024
Opened 2021-02-08 00:20 UTC by GrantMoyer

Adds a new module which shows the state of num lock, caps lock, and scroll lock.

![screencap](https://user-images.githubusercontent.com/6333127/107163806-8a77d300-6979-11eb-8f88-0130753a7906.png)

2021-04-15 19:44 UTC, Alexays commented
Hi, Can you add this module into man?

2021-04-16 12:52 UTC, GrantMoyer commented
It looks like I need to fix the BSD build.

2021-07-21 03:22 UTC, GrantMoyer commented
The build should pass on all test systems now (it passes in my [staging PR][1]). There are a few outdated github actions workflows queued up for this PR, and I'm not sure GitHub will cancel them automatically, so you may want to cancel those manually.

[1]: https://github.com/GrantMoyer/Waybar/pull/1

2021-07-23 13:12 UTC, Alexays requested changes

2021-07-23 13:12 UTC, Alexays commented on src/modules/keyboard_state.cpp
> +    : AModule(config, "keyboard_state", id, false, !config["disable-scroll"].asBool()),
Prefer keyboard-state over keyboard_state

2021-07-23 13:12 UTC, Alexays commented on src/factory.cpp
> +    if (ref == "keyboard_state") {
Prefer keyboard-state over keyboard_state

2021-07-23 13:12 UTC, Alexays commented on resources/style.css
> +#keyboard_state {
Prefer keyboard-state over keyboard_state

2021-07-23 13:12 UTC, Alexays commented on resources/config
> +    "keyboard_state": {
Prefer keyboard-state over keyboard_state

2021-07-23 13:12 UTC, Alexays commented on man/waybar-keyboard-state.5.scd
> +"keyboard_state": {
Prefer keyboard-state over keyboard_state

2021-07-23 14:15 UTC, merged

2021-07-23 14:15 UTC, Alexays commented
Thanks!