Add option to rewrite sway/window title
Alexays/Waybar pull request #1055
Opened 2021-03-21 11:51 UTC by vrld

Rewrites window title according to config option "rewrite".

"rewrite" is an object where keys are regular expressions and values are rewrite rules if the expression matches. Rules may contain references to captures of the expression. Regex and replacement follow ECMA-script rules. If no regex matches, the title is left unchanged.

Useful to add icons depending on the window title, e.g.:
```json
"sway/window": {
  "rewrite": {
    "(.*) - Mozilla Firefox": " $1",
    "(.*) - zsh": " [$1]",
  }
}
```

Examples:
- Firefox:
  -  before ![before patch](https://i.imgur.com/LmBSMUy.png)
  -  patched ![after patch](https://i.imgur.com/mhSCDGr.png)
- Terminal / zsh: 
  - before ![before patch](https://i.imgur.com/0RSj65m.png)
  - patched ![after patch](https://i.imgur.com/Ev0v2U9.png)

2021-03-21 12:33 UTC, vrld commented
Failed test seems to be caused by the runner, not by the changed code:

> ERROR: Clock skew detected. File /Users/runner/work/Waybar/Waybar/build/../subprojects/date-3.0.0/meson_options.txt has a time stamp 10.6111s in the future.

2021-03-31 07:06 UTC, vrld commented
@Alexays is anything missing?

2021-04-15 14:05 UTC, Alexays commented
LGTM, can you update the man in order to add the change?
Thanks!

2021-04-15 14:05 UTC, Alexays approved these changes

2021-04-20 13:53 UTC, Synthetica9 commented
Very cool, using this locally and it's working like a charm! +1 for this feature.

2021-04-20 13:55 UTC, Synthetica9 approved these changes

2021-04-21 08:48 UTC, Synthetica9 requested changes
Actually, I'd like to request 1 change: if the regex is malformed in some way, it's probably better to keep the window title unchanged rather than crapping out completely and not setting the window title at all as is currently the case.

2021-04-21 10:27 UTC, vrld commented
@Synthetica9 Good catch. Added try/catch around the regex stuff to fix this issue

@Alexays Added documentation in manpage and rebased on current master.

2021-04-21 12:23 UTC, Alexays commented
Thx! ❤️ 
Can you also update the Github wiki?

2021-04-21 12:23 UTC, merged

2021-04-21 18:00 UTC, vrld commented
@Alexays done :)