Added support for {gwaddr} as a variable
Alexays/Waybar pull request #1239
Opened 2021-09-09 18:15 UTC by mazunki

I didn't find any way to include the gateway without altering the code. So I did. I greped all the files for `ipaddr`, hoping I catched all the conventions.

I also added a new makefile target (`debug-run`), just because I was annoyed it didn't exist already.

Having `"format-ethernet": "{ipaddr} / {cidr}", "tooltip-format": "{ifname} via {gwaddr}"` feels good and natural. Check the `resources/config` I modified.

2021-09-17 22:51 UTC, Alexays requested changes

2021-09-17 22:51 UTC, Alexays commented on src/modules/network.cpp
> +	spdlog::debug("netwok: gateway {}", net->gwaddr_);
Can you remove this debug and indent `net->gwaddr_ = temp_gw_addr;`?

2021-09-18 00:06 UTC, mazunki commented
Thanks for checking it out, @Alexays . Commit 5f08319 updates the changes requested. 

I also fixed the Makefile dependency from default build to debug build. The 6142dfb is a suggestion, to include the gateway IP in the debug log, feel free to take it or leave it.

As a note, I recently updated my kernel, and there seems to be an issue with reaching the case block for the `RTA_GATEWAY`, which worked when I pushed the commit.

While it still works on the standalone script [I initially tested on](https://gist.github.com/mazunki/e44181731294baad3bb1c8fc7cb7667f), it doesn't seem to work through the Waybar script.

I haven't yet looked much into what's going on here.

2021-09-18 11:47 UTC, Alexays commented
Thanks!
Can you also update the Github wiki?

2021-09-18 11:47 UTC, merged

2021-09-18 12:31 UTC, mazunki commented
Perfect! I updated the wiki too. I'm surprised there weren't any permission limitations for editing it. Is that a default behaviour of GitHub?