[WIP] Add ability to use icons for language module
Alexays/Waybar pull request #984
Opened 2021-01-16 04:43 UTC by 3ap

2021-01-21 21:04 UTC, alebastr requested changes
Looking at the other modules, the common style is to define getIcon method and use it for the `icon` argument. Something like
```c++
std::string Language::getIcon(const std::string& lang) {
  auto icons = config_["format-icons"];
  if (icons.isObject() && icons[lang].isString()) {
    return icons[lang].asString();        
  }
  // default to name if no icon is configured
  return lang;
}
// ...
fmt::format(format_, fmt::arg("language", lang_), fmt::arg("icon", getIcon(lang_)));
// ...

2021-02-04 09:09 UTC, Alexays requested changes

2021-02-04 09:09 UTC, Alexays commented on src/ALabel.cpp
> +std::string ALabel::getIcon(const std::string& key) {
You should define getIcon in the language class :)

2021-04-30 12:29 UTC, Alexays requested changes

2021-04-30 12:29 UTC, Alexays commented on src/modules/sway/language.cpp
> +    label_.set_markup(fmt::format(format_,
You should also keep default arg for config compability purpose

2021-08-28 14:49 UTC, closed without merging